### ISSUE TITLE
[BUG]: Lid actions

### ISSUE THREAD

**Issue by Edgars-Cirulis** [meetrevision/playbook#119]
### Describe the bug

The commit https://github.com/meetrevision/playbook/commit/507fd54e819eae67b7e5e67ae54abb51229c2735 did not fix issue https://github.com/meetrevision/playbook/issues/105. I saved the lid actions that were working on apply, and while reapplying the playbook, it saved the layout settings I had changed, but I need to reapply them to make it work.

### Steps to reproduce

1. Set LID actions in power settings to "Do nothing," save it, and it works.
2. Reapply the playbook.
3. LID action settings were saved, but they don't work; it goes to sleep mode. So, I need to reapply the settings from "Do Nothing" to "Sleep" and again to "Do Nothing."

### Expected behavior

I expected that the PC wouldn't go to sleep with lid closed after reapplying the playbook.

### Environment

- OS Build Number & Edition: `Latest 11 Pro 23H2`
- ReviOS Version: https://github.com/meetrevision/playbook/commit/d1d4bbc72561c2cf59fbcc3c4a55f752c450bbb3

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
The most recent fix works as intended. After the release of 23.12, during the testing phase, the playbook was designed to reset, hide, or delete every power plan except for Revision's.

Resetting Revision's power plan is mandatory when applying the playbook, and providing toggle or revert options would lead to unexpected performance behaviors because hidden power plan settings change periodically.

**Comment by Edgars-Cirulis** [comment]
Dunno, I'll make a video about it to prove that it doesn't fix. It still makes computer in sleep after replying playbook even tho it says lid actions: do nothing. If I replied the same value from from do nothing to sleep then do nothing it works again.
