### ISSUE TITLE
[BUG]: ReviOS playbook applied with errors

### ISSUE THREAD

**Issue by sleel** [meetrevision/playbook#131]
### Describe the bug

The installation of ReviOS in AME Wizard always ended up with "ReviOS playbook is applied with errors"

After reboot, run AME Wizard and install Revios again, it shows that the installation was successful. 

The logs are as follows: 
[Logs.zip](https://github.com/user-attachments/files/16799299/Logs.zip)

### Steps to reproduce

1. Deploy ReviOS in AME Wizard
2. 
3. 
4. 

### Expected behavior

I expected ReviOS to be correctly applied.

### Environment

OS Build Number & Edition: Windows 11 23H2 Build 22631.4037
ReviOS Version: v24 06
Specs: type here

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by Pyenb** [comment]
Taken from @melo936 

"In recent cumulative updates, Windows Updates have added locks on certain registries. In next playbook update, we will silence the errors. But to apply the registries on your system, AME team will have to do something. The reason why the playbook finishes with no errors on second run is because Windows Updates are paused."

So in short, will get a temp-fix, but we mainly have to wait for the team behind the AME Wizard to fix it.
