### ISSUE TITLE
[BUG] Can't disable windows defender

### ISSUE THREAD

**Issue by n4skx** [meetrevision/playbook#16]
After i followed the steps from https://revi.cc/docs/faq/after/defender the windows defender isn't disabled. Is this 'tutorial' patched or something like that?

**Comment by dreammjow** [comment]
Firstly, check if Defender services are running, because Revision Tool has a bug at detecting Defender status, it shows enabled when TamperProtection is enabled even if the defender's services and drivers are disabled. 

If they are running, try to boot in safe mode, open Revision Tool, disable Defender and boot in normal mode.

**Comment by n4skx** [comment]
Thank you!
