### ISSUE TITLE
What is this thing?

### ISSUE THREAD

**Issue by allanonmage** [meetrevision/playbook#17]
Came across your project from the Ameliorated page.  Aside from some branding, I have - idea what differentiates your playbook compared to the default/stock one that the Ameliorated project offers.  I've read your website and the elevator pitch here on Github and still don't get it.  Please explain.

I don't have discord because they banned me while I was signing up, which I should expect from anyone else using Ameliorated, so I'm not sure why that's you're sole point of contact.  It's my understanding that Discord has bought into the "verified person" concept plaguing tech right now, which is anethma to something like Ameliorated, so I don't understand why your userbase would all have Discord accounts.

**Comment by dreammjow** [comment]
You can see differences between ReviOS and stock [here](https://www.revi.cc/docs/faq/before/features).

Regarding to the Discord topic, Revision server is a tweaking community which means it isn't only dedicated to ReviOS. the project was started on Discord and we use it since then for support. I don't understand "They banned me while I was signing up, which I should expect from anyone else using Ameliorated", what does AME has to do with your sign up issue? If you are talking about server bans, you probably getting banned, because your account is new.

**Comment by nomonkeynodeal** [comment]
I can't get into discord either. It's because I don't have an official enough phone number from an approved provider such as Verizon or AT&T. If someone uses VOIP phone numbers, should they be not allowed to get information about ReviOS?

ReviOS and the entire AME project came into existence because of exactly this kind of corporate intransigence and gatekeeping. I don't understand why any new tech projects use Discord at all. It's the same as using a Facebook group.
