### ISSUE TITLE
[BUG]: Cumulative Updates Fail To Install

### ISSUE THREAD

**Issue by melo936** [meetrevision/playbook#49]
### Describe the bug

Installing latest cumulative updates via Windows Updates on ReviOS is partially broken, leading to errors such as 0x800f0984. While our [documentation](https://www.revi.cc/docs/playbook/upgrade#errors-during-updates) offers solutions for this issue, it is not an ideal and can be time-consuming.

Updates like ".NET Cumulative Updates" are not affected.

One of the main reasons could be the following command:
https://github.com/meetrevision/playbook/blob/607c6f13d3425b6afa6b22e85390c286e587099a/src/Executables/CLEANER.ps1#L84-L85

### Steps to reproduce

1. Unhide and Resume Windows Updates via Revision Tool
2. Navigate to the Windows Updates page
3. Get Updates
4. Cumulative Updates fails to install

### Expected behavior

Cumulative Updates must install without any errors

### Environment

- OS Build Number & Edition: `22631.2506 & Home`
- ReviOS Version: `23.10`
- Specs: 

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by Edgars-Cirulis** [comment]
So fix this 😁

**Comment by Sthaagg** [comment]
I managed to install it on my side by following these steps:

1. Set group policy "Specify settings for optional component installation and component repair" to enabled (under Local Computer / Computer Configuration / Administrative Template)
2. Download "Reset Windows Update Tool" (from [)](https://wureset.com/), portable version)
3. I pick Step 2 / 6 / 8 / 9 (not sure 6 & 8 are mandatory)
4. Run Windows Update

After that you need to rerun the playbook to restore everything.

**Comment by JL2210** [comment]
Similar issue here. Will try inplace upgrade if wureset doesn't work. Although I think my PC is hanging on the error right now.

**Comment by Eloston** [comment]
@JL2210 If you're using 23H2, I would be careful about Method 1.

I had 23H2 on a machine. I tried re-installing 23H2 using the same ISO after the cumulative updates failed, and then my task bar broke (disappeared completely). Unless the MVS ISOs are different than normal retail ISOs, I expect the task bar would still disappear. For more context, it's the same task bar issue people experience when upgrading from 22H2 to 23H2 (I experienced this too).

Some other attempts to fix it also failed:
- I tried a Powershell command to reinstall Appx packages for the current user, but some of the core packages failed to install because they're corrupted (phrasing my own, I forgot the error code).
- When my 23H2 had a broken task bar, I also tried Method 2's DISM command to attempt to fix it, but it fails because the original system files are corrupted (phrasing is my own).

I have a machine running 23H2 but missing the recent cumulative update. Hopefully wureset works for me.

**Comment by JL2210** [comment]
@Eloston Actually I tried wureset again after rebooting a couple times (both restart and shut down/turn on) and the cumulative update was able to install. Now the Microsoft Defender update won't work. Not a huge issue, since I have it disabled.

I had a similar problem with the task bar disappearing when 23H2 came out. I think I had to unpack the installer ISO to a folder on my desktop and wipe all my data to fix it.

These problems are really disheartening, especially since I'm infinitely less proficient in Windows than I am at Linux. Doesn't help that the error logs are all just 0x800yzxyz. Basically the extent of the advice for anything is: 1. run dism! run sfc! 2. Delete your entire computer.

**Comment by Eloston** [comment]
> These problems are really disheartening, especially since I'm infinitely less proficient in Windows than I am at Linux. Doesn't help that the error logs are all just 0x800yzxyz. Basically the extent of the advice for anything is: 1. run dism! run sfc! 2. Delete your entire computer.

100% in the same position. I'm a toddler when it comes to Windows internals.

I also just got wureset to work with just Steps 2 and 9 in the tool. Worked first try, no rebooting needed. Thanks @Sthaagg for informing us about the tool!

**Comment by Sthaagg** [comment]
The taskbar problem is a known issue by Microsoft, thought it was fixed.
That's why i try to get files from network instead of the one from the ISO / System image

**Comment by melo936** [comment]
The issue should be resolved. To test it:

- Download and install Windows 11 23H2 ISO
    - Follow [our documentation](https://www.revi.cc/docs/playbook/installstock/) to install Windows and to avoid online account requirements, auto Windows Updates and drivers installation, etc.
- Apply the [23.11-1](https://github.com/meetrevision/playbook/releases/tag/23.11-1) playbook
- Once everything is done, enable Windows Updates via Revision Tool
- Go to Windows Settings → Windows Updates, click on "Check for updates" and it will automatically download and install updates.

Make sure to report it back!
